package com.loanflow.loanflow.dto;

import com.loanflow.loanflow.entity.UserRole;
import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * Data Transfer Object (DTO) returned after successful authentication.
 *
 * This response is sent to the client when a user logs in successfully
 * and contains the information required for:
 *  - Maintaining authenticated sessions on the frontend
 *  - Displaying user identity and role-based UI
 *  - Sending JWT token with subsequent API requests
 */
@Data
@AllArgsConstructor
public class LoginResponse {

    /**
     * JWT token generated by the backend.
     * The frontend stores this token and sends it in the Authorization header
     * for all protected API calls.
     */
    private String token;

    /**
     * Authenticated user's username.
     */
    private String username;

    /**
     * Role assigned to the authenticated user.
     * Used for role-based access control and UI permissions.
     */
    private UserRole role;
}
